spring:

  datasource:
    url: jdbc:mysql://localhost:3306/projekt_tool
    username: root
    password: user

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true





