version: '3.6'

services:


  backend:
    container_name: ProjectTools
    build:
      context: .
    depends_on:
      - db

  db:
    image: 'mysql:8'
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE : tool
      MYSQL_ROOT_PASSWORD : db#1234

